#!/usr/bin/env julia

using Pkg
Pkg.activate(normpath(@__DIR__))

using Raytracing

function main()
	Raytracing.greet()

	a = RGB{Float64}(0.1, 0.3, 0.7)
	println("a")
	b = RGB{Float64}(0.2, 0.6, 0.0)
	println("b")

	println(a+b)
	println("c")
	
end

main()


