#!/usr/bin/env julia.exe

using Pkg
Pkg.activate(normpath(@__DIR__))

using Colors, Images, ImageIO
using ColorTypes:RGB
using Raytracing

function main(args)
	if isempty(args) || length(args)==1 || length(args)>4
        println("\ncorrect usage: ./main input_pfm_filename output_png_filename [a , [γ]]")
	   return nothing
	end  

	parameters = nothing
	try
		parameters =  Parameters(parse_command_line(args)...)
	catch e
		println("Error: ", e)
		return nothing
	end

	img = open(parameters.infile, "r") do inpf; read(inpf, HDRimage); end
	
	println("\nfile $(parameters.infile) has been read from disk.\n")

	normalize_image!(img, parameters.a)
	clamp_image!(img)
	γ_correction!(img, parameters.γ)
	matrix = get_matrix(img)

	println(img, 3)
	Images.save(parameters.outfile, overturn(matrix))
	#Images.save(Images.File(PNG,parameters.outfile), img.rgb_m)
	#Images.save(File("PNG", parameters.outfile), img.rgb_m)

	println("\nFile $(parameters.outfile) has been written into the disk.\n")

	return nothing
end

main(ARGS)